import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { generateArrayKey } from "@/lib/utils/array-utils";

const faqData = [
  {
    question: "What is Obby and how does it work?",
    answer:
      "Obby is an AI-powered development assistant that helps you build Next.js apps by simply describing what you want to create. Using advanced AI models, Obby generates clean, production-ready code that you can customize and deploy immediately. Just describe your project in natural language, and Obby will create the complete application structure, components, and functionality for you.",
  },
  {
    question: "What does the free plan include?",
    answer:
      "The free plan includes 20 monthly credits, limited agent use, basic project creation, community support, and standard attachment size limits. This gives you enough credits to explore Obby's capabilities and build small projects. You can create multiple projects, experiment with different tech stacks, and get a feel for how Obby works before upgrading to a paid plan.",
  },
  {
    question: "What tech stacks does Obby know?",
    answer:
      "Obby is proficient in modern web technologies including React, Next.js, Vue, Svelte, Node.js, TypeScript, JavaScript, Tailwind CSS, and many popular libraries and frameworks. It can generate full-stack applications with databases, authentication, APIs, and deployment configurations. Obby stays up-to-date with the latest best practices and can work with both frontend and backend technologies.",
  },
  {
    question: "Who owns the projects and code?",
    answer:
      "You own all the code and projects generated by Obby. Once Obby creates your application, you have full ownership and can modify, distribute, or commercialize it as you see fit. There are no licensing restrictions on the generated code, and you're free to use it for personal or commercial purposes without any attribution requirements.",
  },
  {
    question: "How much does it cost to use?",
    answer:
      "Obby offers three pricing tiers: Free ($0/month) with 20 credits, Premium ($20/month) with 100 credits and advanced features, and Team ($30/user/month) with collaboration tools and team management. Credits are used when you generate code or use AI features. You can start with the free plan and upgrade as your needs grow.",
  },
  {
    question: "Can I collaborate with my team?",
    answer:
      "Yes! With the Team plan, you can share chats between team members, manage users through an admin panel, and collaborate on projects in real-time. Team features include shared workspaces, project permissions, and advanced analytics to track your team's usage and productivity.",
  },
  {
    question: "What file types can I upload?",
    answer:
      "Obby supports various file types including images (PNG, JPG, SVG, Webp), design files (Figma imports on Premium), and code files. Premium users get 5x higher attachment size limits, allowing you to upload larger files and more complex project assets.",
  },
  {
    question: "Can I cancel my subscription anytime?",
    answer:
      "Yes, you can cancel your subscription at any time. If you cancel, you'll continue to have access to your paid features until the end of your current billing period, after which your account will revert to the free plan. All your projects and data remain accessible even after cancellation.",
  },
];

export function FAQSection() {
  return (
    <Accordion type="single" collapsible className="w-full space-y-4">
      {faqData.map((faq, index) => (
        <AccordionItem
          key={`faq-${generateArrayKey(index)}`}
          value={`item-${generateArrayKey(index)}`}
          className="border border-border rounded-lg px-6 py-2 bg-card"
        >
          <AccordionTrigger className="text-left hover:no-underline py-4">
            <span className="text-base font-medium">{faq.question}</span>
          </AccordionTrigger>
          <AccordionContent className="pb-4 pt-2">
            <p className="text-muted-foreground leading-relaxed">
              {faq.answer}
            </p>
          </AccordionContent>
        </AccordionItem>
      ))}
    </Accordion>
  );
}
